# Automatically generated by hassfest.
#
# To update, run python3 -m script.hassfest -p docker
FROM python:3.14-slim

LABEL org.opencontainers.image.source="https://github.com/home-assistant/core"

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /usr/src/homeassistant

# Ensure package constraints referenced by requirements.txt are present
# (requirements.txt contains: -c homeassistant/package_constraints.txt)
COPY homeassistant/package_constraints.txt homeassistant/package_constraints.txt

# Install minimal build tools needed to build wheels for some packages
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       build-essential \
       gcc \
       g++ \
       libffi-dev \
       libssl-dev \
       libjpeg-dev \
       zlib1g-dev \
       pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Copy pinned requirements and install them (no pinning in Dockerfile)
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Install test dependencies so `pytest` is available in the image
# Copy any files referenced by requirements_test.txt
COPY requirements_test.txt ./
COPY requirements_test_pre_commit.txt ./
RUN pip install --no-cache-dir -r requirements_test.txt

# Copy source and install package in editable mode
COPY . /usr/src/homeassistant
RUN pip install --no-cache-dir -e .

# Default working directory for runtime/test commands
WORKDIR /usr/src/homeassistant

# Run tests by default if present
CMD ["pytest", "tests"]
